# Generated by Django 4.2.10 on 2026-04-30 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientdomain',
            options={'ordering': ['domain']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='parent_tenant',
            field=models.ForeignKey(blank=True, help_text='Parent tenant for shops (linked to University or Location)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tenants', to='app.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='tenant_type',
            field=models.CharField(choices=[('university', 'University'), ('location', 'Location/Area'), ('shop', 'Shop')], db_index=True, default='public', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant_type', 'on_trial'], name='app_client_tenant__3c3e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['parent_tenant', 'tenant_type'], name='app_client_parent__b16644_idx'),
        ),
    ]
