# Generated by Django 4.2.10 on 2026-04-30 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_options_alter_clientdomain_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Dark Luxury', 'Light Enterprise'", max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier', unique=True)),
                ('description', models.TextField(blank=True)),
                ('theme_type', models.CharField(choices=[('global', 'Global Site Theme'), ('page-specific', 'Page-Specific Override'), ('variant', 'Design Variant'), ('accessibility', 'Accessibility Mode')], default='global', max_length=20)),
                ('token_overrides', models.JSONField(blank=True, default=dict, help_text='Map of token_name -> value overrides')),
                ('custom_css', models.TextField(blank=True, help_text='Additional CSS rules specific to this theme')),
                ('is_active', models.BooleanField(default=False, help_text='Is this the current active theme?')),
                ('is_public', models.BooleanField(default=False, help_text='Should this be visible to users?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'primary-blue', 'space-4', 'font-body'", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('color', 'Color'), ('spacing', 'Spacing'), ('typography', 'Typography'), ('radius', 'Border Radius'), ('shadow', 'Shadow'), ('effect', 'Effect/Filter'), ('layout', 'Layout')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='What this token is used for')),
                ('default_value', models.CharField(help_text='CSS value: hex color, px value, font stack, etc.', max_length=500)),
                ('is_global', models.BooleanField(default=True, help_text='If True, affects all pages; if False, can be overridden per-theme')),
                ('css_custom_property', models.CharField(help_text='CSS custom property name: --primary-blue', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('token-update', 'Token Value Changed'), ('css-update', 'Custom CSS Updated'), ('theme-created', 'Theme Created'), ('theme-activated', 'Theme Activated'), ('component-mock', 'Component Mocked'), ('component-published', 'Component Published')], max_length=20)),
                ('changed_field', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Why this change was made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.theme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageThemeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('homepage', 'Homepage'), ('explore', 'Explore/Directory'), ('listings', 'Listings'), ('shop-detail', 'Shop Detail'), ('listing-detail', 'Listing Detail'), ('about', 'About'), ('contact', 'Contact'), ('admin', 'Admin Dashboard'), ('custom', 'Custom Page')], max_length=50, unique=True)),
                ('page_route', models.CharField(blank=True, help_text='Django URL name or pattern. Leave blank for page_type auto-detection', max_length=255)),
                ('override_enabled', models.BooleanField(default=True, help_text='If False, uses global active theme')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.theme')),
            ],
            options={
                'verbose_name': 'Page Theme Assignment',
                'verbose_name_plural': 'Page Theme Assignments',
                'ordering': ['page_type'],
            },
        ),
        migrations.CreateModel(
            name='ThemeComponentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'NavBar', 'ProductCard'", max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('html_template', models.TextField(help_text='Template HTML (can use Django template syntax)')),
                ('inline_css', models.TextField(blank=True, help_text='CSS specific to this component')),
                ('inline_js', models.TextField(blank=True, help_text='JavaScript for interactivity')),
                ('version', models.IntegerField(default=1, help_text='Version number for iterations')),
                ('is_published', models.BooleanField(default=False, help_text='Is this version live?')),
                ('is_draft', models.BooleanField(default=True, help_text='Is this a draft/mock?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.theme')),
            ],
            options={
                'ordering': ['-is_published', 'name', '-version'],
                'unique_together': {('slug', 'version')},
            },
        ),
    ]
