# Generated by Django 4.2.10 on 2026-05-01 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_theme_themetoken_themechangelog_pagethemeassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(help_text='Snapshot of username at time of action', max_length=150)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('export', 'Export'), ('bulk_action', 'Bulk Action'), ('permission_grant', 'Permission Granted'), ('permission_revoke', 'Permission Revoked'), ('login', 'Admin Login'), ('logout', 'Admin Logout'), ('failed_auth', 'Failed Auth Attempt'), ('setting_change', 'Settings Changed'), ('ban_user', 'User Banned'), ('unban_user', 'User Unbanned'), ('approve_listing', 'Listing Approved'), ('reject_listing', 'Listing Rejected'), ('feature_listing', 'Listing Featured'), ('unfeature_listing', 'Listing Unfeatured'), ('process_refund', 'Refund Processed'), ('other', 'Other')], max_length=30)),
                ('action_label', models.CharField(blank=True, help_text="Human-readable action description (e.g., 'Approved listing #123')", max_length=255)),
                ('content_type', models.CharField(help_text="Model name (e.g., 'User', 'Shop', 'Listing')", max_length=100)),
                ('object_id', models.CharField(help_text='ID of affected object', max_length=255)),
                ('object_str', models.CharField(blank=True, help_text='String representation of object at time of action', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dict of {field: {old: value, new: value}}')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Complete snapshot of object before change')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='Complete snapshot of object after change')),
                ('reason', models.TextField(blank=True, help_text='Why the action was taken (from form or comment)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client info')),
                ('related_objects', models.JSONField(blank=True, default=list, help_text='List of related object IDs affected (for bulk ops)')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial_success', 'Partial Success'), ('error', 'Error'), ('pending', 'Pending')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='app_adminau_admin_u_c810c1_idx'), models.Index(fields=['action', '-created_at'], name='app_adminau_action_178cb1_idx'), models.Index(fields=['content_type', 'object_id'], name='app_adminau_content_dde55f_idx'), models.Index(fields=['-created_at'], name='app_adminau_created_9b0c12_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Admin Logged In'), ('logout', 'Admin Logged Out'), ('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('banned', 'User Banned'), ('feature', 'Featured'), ('unfeature', 'Unfeatured'), ('refund', 'Refund Processed'), ('system', 'System Event')], max_length=20)),
                ('content_type', models.CharField(help_text='e.g., User, Shop, Listing', max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('object_title', models.CharField(blank=True, help_text='e.g., user email, shop name, listing title', max_length=500)),
                ('description', models.CharField(help_text="Short summary for dashboard (e.g., 'Admin approved listing #123')", max_length=500)),
                ('icon', models.CharField(blank=True, default='activity', help_text='Bootstrap icon name (bi-*)', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=20)),
                ('link_url', models.CharField(blank=True, help_text='Admin URL to the affected object', max_length=500)),
                ('batch_id', models.CharField(blank=True, db_index=True, help_text='ID for grouping related bulk actions', max_length=100)),
                ('is_visible', models.BooleanField(default=True, help_text='Show in activity feed?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_feed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='app_adminac_admin_u_5f5cea_idx'), models.Index(fields=['activity_type', '-created_at'], name='app_adminac_activit_776db6_idx'), models.Index(fields=['content_type', 'object_id'], name='app_adminac_content_ce6a2c_idx')],
            },
        ),
    ]
