# Generated by Django 4.2.10 on 2026-05-02 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_adminauditlog_adminactivityfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themechangelog',
            name='change_type',
            field=models.CharField(choices=[('token-update', 'Token Value Changed'), ('css-update', 'Custom CSS Updated'), ('theme-created', 'Theme Created'), ('theme-activated', 'Theme Activated'), ('theme-updated', 'Theme Updated'), ('theme-published', 'Theme Published'), ('theme-unpublished', 'Theme Unpublished'), ('theme-deleted', 'Theme Deleted'), ('component-mock', 'Component Mocked'), ('component-published', 'Component Published')], max_length=20),
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stk_push', 'STK Push - Customer Payment Prompt'), ('stk_status', 'STK Status - Payment Status Poll'), ('b2c', 'B2C - Business to Customer Disbursement'), ('reversal', 'Reversal - Undo Transaction')], db_index=True, help_text='Type of M-PESA transaction', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending - Awaiting response'), ('success', 'Success - Payment completed'), ('failed', 'Failed - Payment rejected or cancelled')], db_index=True, default='pending', help_text='Current transaction status', max_length=20)),
                ('phone', models.CharField(db_index=True, help_text='Customer/recipient phone in format 254XXXXXXXXX', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KES', max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Transaction reference / order ID', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Human-readable description of transaction', max_length=255)),
                ('b2c_command_id', models.CharField(blank=True, choices=[('BusinessPayment', 'Business Payment'), ('SalaryPayment', 'Salary Payment'), ('PromotionPayment', 'Promotion Payment')], help_text='B2C transaction type (BusinessPayment, SalaryPayment, etc.)', max_length=20)),
                ('remarks', models.CharField(blank=True, help_text='Remarks sent with B2C transaction', max_length=255)),
                ('occasion', models.CharField(blank=True, help_text='Occasion/reason for B2C payment', max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, help_text='MerchantRequestID from M-PESA API', max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, help_text='CheckoutRequestID from STK Push (for polling status)', max_length=100, unique=True)),
                ('conversation_id', models.CharField(blank=True, db_index=True, help_text='ConversationID from M-PESA API response', max_length=100)),
                ('originator_conversation_id', models.CharField(blank=True, help_text='OriginatorConversationID from M-PESA API', max_length=100)),
                ('receipt', models.CharField(blank=True, db_index=True, help_text='M-PESA receipt number (on success)', max_length=20)),
                ('result_code', models.CharField(blank=True, help_text='Result code from M-PESA API', max_length=10)),
                ('result_description', models.TextField(blank=True, help_text='Result description from M-PESA (success/failure reason)')),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Complete request sent to M-PESA API')),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='Complete response from M-PESA API')),
                ('rate_limit_remaining', models.IntegerField(blank=True, help_text='Remaining API quota after this request', null=True)),
                ('rate_limit_total', models.IntegerField(blank=True, help_text='Total daily API quota', null=True)),
                ('rate_limit_reset', models.DateTimeField(blank=True, help_text='When the rate limit counter resets', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed (success or failed)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when transaction was initiated', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client info')),
                ('notes', models.TextField(blank=True, help_text='Admin notes or transaction details')),
                ('shop', models.ForeignKey(blank=True, help_text='Shop associated with transaction (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='app.client')),
                ('user', models.ForeignKey(blank=True, help_text='User initiating the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-PESA Transaction',
                'verbose_name_plural': 'M-PESA Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_mpesatr_user_id_3dd15f_idx'), models.Index(fields=['status', '-created_at'], name='app_mpesatr_status_40c26c_idx'), models.Index(fields=['phone', '-created_at'], name='app_mpesatr_phone_c6e3ab_idx'), models.Index(fields=['receipt'], name='app_mpesatr_receipt_c8bb9a_idx'), models.Index(fields=['checkout_request_id'], name='app_mpesatr_checkou_98e6f4_idx'), models.Index(fields=['transaction_type', '-created_at'], name='app_mpesatr_transac_e542d8_idx')],
            },
        ),
    ]
