# Generated by Django 4.2.10 on 2026-04-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydak', '0005_category_listing_condition_listing_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='mydak.listing'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Debit/Credit Card'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for M-Pesa transactions (254XXXXXXXXX)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated (STK Sent)'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method', 'status'], name='mydak_trans_payment_d38299_idx'),
        ),
    ]
