# Generated by Django 4.2.10 on 2026-04-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydak', '0008_listingtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('local_pickup', 'Local Pickup'), ('posta', 'Posta (National)'), ('jiji', 'Jiji Courier'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('custom', 'Custom Courier')], max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('estimated_days_min', models.IntegerField(default=1, help_text='Min delivery days')),
                ('estimated_days_max', models.IntegerField(default=5, help_text='Max delivery days')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_min_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight_max_kg', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='mydak.shippingcarrier')),
            ],
            options={
                'ordering': ['weight_min_kg'],
                'unique_together': {('carrier', 'weight_min_kg', 'weight_max_kg')},
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mydak.shippingcarrier')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_options', to='mydak.listing')),
            ],
            options={
                'unique_together': {('listing', 'carrier')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mydak.shippingcarrier')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='mydak.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_number', 'status'], name='mydak_shipm_trackin_d9a0d3_idx')],
            },
        ),
    ]
