# Generated by Django 4.2.10 on 2026-04-30 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydak', '0009_shippingcarrier_shippingrate_shippingoption_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('auto_relist', 'Auto-relist Expired'), ('price_adjust', 'Adjust Price'), ('auto_decline', 'Auto-decline Low Offers'), ('auto_feature', 'Auto-feature Listings'), ('auto_republish', 'Auto-republish Old Listings')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('condition_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('action_param_1', models.CharField(blank=True, max_length=255)),
                ('action_param_2', models.CharField(blank=True, max_length=255)),
                ('condition_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mydak.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_rules', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='mydak.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'shop', 'is_active'], name='mydak_selle_seller__e824eb_idx'), models.Index(fields=['rule_type'], name='mydak_selle_rule_ty_ed8c13_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_acceptable_price_percent', models.IntegerField(default=80)),
                ('auto_decline_below_percent', models.BooleanField(default=False)),
                ('auto_counter_offer', models.BooleanField(default=False)),
                ('counter_offer_percent', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_rules', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_rules', to='mydak.shop')),
            ],
            options={
                'unique_together': {('shop', 'seller')},
            },
        ),
    ]
